[package]
name = "game-data-audit"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
xiv-gen.workspace = true
rkyv = { version = "0.7.42", features = ["validation", "size_32", "std", "hashbrown"], default-features = false }
brotli = "8.0.4"
flate2 = "1.1.9"
sha2 = "0.10"

[build-dependencies]
syn = { version = "2", features = ["full"] }
