FROM ghcr.io/cross-rs/aarch64-unknown-linux-musl:latest

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install --assume-yes libfreetype6-dev:arm64 libwebp-dev:arm64 libfontconfig1-dev:arm64 libfontconfig1-dev clang