# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:15
    command: postgres -c 'max_connections=300'
    restart: always
    environment:
        POSTGRES_USER: ultros
        POSTGRES_PASSWORD: ultrosislinodetime 
        POSTGRES_DB: ultros
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8050:8050
  ultros:
    image: ultros
    restart: always
    ports: 
      - 8080:8080
    env_file:
      - .env
