//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// One materia slotted into a listed item, as reported by Universalis.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Materia {
    pub slot_id: Option<i32>,
    pub materia_id: i32,
}

/// The full materia loadout of a listing, stored as a jsonb column.
///
/// Universalis' change diff compares only (listingID, price, quantity), so
/// materia mutations emit no websocket events — this field is only as fresh as
/// the last REST board fetch for the item.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult, Default)]
pub struct MateriaList(pub Vec<Materia>);

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "active_listing")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i32,
    pub world_id: i32,
    pub item_id: i32,
    pub retainer_id: i32,
    pub price_per_unit: i32,
    pub quantity: i32,
    pub hq: bool,
    pub timestamp: DateTime,
    /// Universalis' stable listing identity (`listingID`). Null on rows
    /// ingested before the identity migration and on payloads lacking the id;
    /// unique per (world_id, item_id) when present.
    pub listing_id: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub materia: Option<MateriaList>,
    pub stain_id: Option<i32>,
    pub creator_name: Option<String>,
    pub is_crafted: bool,
    pub on_mannequin: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::materia_listing::Entity")]
    MateriaListing,
    #[sea_orm(
        belongs_to = "super::retainer::Entity",
        from = "Column::RetainerId",
        to = "super::retainer::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Retainer,
    #[sea_orm(
        belongs_to = "super::world::Entity",
        from = "Column::WorldId",
        to = "super::world::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    World,
}

impl Related<super::materia_listing::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MateriaListing.def()
    }
}

impl Related<super::retainer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Retainer.def()
    }
}

impl Related<super::world::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::World.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
