//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "alert")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub owner: i64,
    pub enabled: bool,
    pub last_fired_at: Option<DateTimeWithTimeZone>,
    pub cooldown_seconds: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::alert_discord_destination::Entity")]
    AlertDiscordDestination,
    #[sea_orm(has_many = "super::alert_event::Entity")]
    AlertEvent,
    #[sea_orm(has_many = "super::alert_item_threshold::Entity")]
    AlertItemThreshold,
    #[sea_orm(has_many = "super::alert_list_threshold::Entity")]
    AlertListThreshold,
    #[sea_orm(has_many = "super::alert_list_update::Entity")]
    AlertListUpdate,
    #[sea_orm(has_many = "super::alert_retainer_undercut::Entity")]
    AlertRetainerUndercut,
    #[sea_orm(
        belongs_to = "super::discord_user::Entity",
        from = "Column::Owner",
        to = "super::discord_user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    DiscordUser,
}

impl Related<super::alert_discord_destination::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlertDiscordDestination.def()
    }
}

impl Related<super::alert_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlertEvent.def()
    }
}

impl Related<super::alert_item_threshold::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlertItemThreshold.def()
    }
}

impl Related<super::alert_list_threshold::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlertListThreshold.def()
    }
}

impl Related<super::alert_list_update::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlertListUpdate.def()
    }
}

impl Related<super::alert_retainer_undercut::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlertRetainerUndercut.def()
    }
}

impl Related<super::discord_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
