//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "alert_notification_rule")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub alert_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub endpoint_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::alert::Entity",
        from = "Column::AlertId",
        to = "super::alert::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Alert,
    #[sea_orm(
        belongs_to = "super::notification_endpoint::Entity",
        from = "Column::EndpointId",
        to = "super::notification_endpoint::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    NotificationEndpoint,
}

impl Related<super::alert::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Alert.def()
    }
}

impl Related<super::notification_endpoint::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationEndpoint.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
