//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "discord_user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub username: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::owned_ffxiv_character::Entity")]
    OwnedFfxivCharacter,
    #[sea_orm(has_one = "super::ffxiv_character_verification::Entity")]
    FfxivCharacterVerification,
    #[sea_orm(has_many = "super::alert::Entity")]
    Alert,
}

impl Related<super::owned_ffxiv_character::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OwnedFfxivCharacter.def()
    }
}

impl Related<super::ffxiv_character_verification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FfxivCharacterVerification.def()
    }
}

impl Related<super::alert::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Alert.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
