//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "materia_listing")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub materia_id: Option<i32>,
    pub slot: Option<i16>,
    #[sea_orm(unique)]
    pub active_listing_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::active_listing::Entity",
        from = "Column::ActiveListingId",
        to = "super::active_listing::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ActiveListing,
}

impl Related<super::active_listing::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActiveListing.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
