//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "notification_endpoint")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i64,
    pub name: String,
    pub method: String,
    pub config: Json,
    pub created_at: DateTimeUtc,
    /// Set when delivery hit a *permanent* failure (channel deleted, bot
    /// removed) and we stopped retrying. `None` means healthy.
    pub disabled_at: Option<DateTimeUtc>,
    /// Human-readable reason the endpoint was disabled, surfaced by the
    /// endpoints UI. Cleared alongside `disabled_at` when a delivery or an
    /// explicit Test succeeds, so it only ever describes a *current* outage.
    pub last_error: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::discord_user::Entity",
        from = "Column::UserId",
        to = "super::discord_user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    DiscordUser,
    #[sea_orm(has_many = "super::alert_notification_rule::Entity")]
    AlertNotificationRule,
}

impl Related<super::discord_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordUser.def()
    }
}

impl Related<super::alert_notification_rule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlertNotificationRule.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
