//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "price_alert")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub list_id: i32,
    pub alert_id: i32,
    pub world_id: Option<i32>,
    pub datacenter_id: Option<i32>,
    pub region_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
