//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "sale_history")]
pub struct Model {
    pub quantity: i32,
    pub price_per_item: i32,
    pub buying_character_id: i32,
    pub hq: bool,
    #[sea_orm(primary_key, auto_increment = false)]
    pub sold_item_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub sold_date: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub world_id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub buyer_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::world::Entity",
        from = "Column::WorldId",
        to = "super::world::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    World,
}

impl Related<super::world::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::World.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
