name: Book Check

on:
    pull_request:

permissions:
    contents: read

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install latest mdBook
              uses: peaceiris/actions-mdbook@v2
              with:
                  mdbook-version: "latest"


            - name: Build book
              run: |
                  cd userguide
                  mdbook build
